# Generated by Django 5.2.1 on 2025-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
