# Generated by Django 5.2.1 on 2025-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_like_liked_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_at',
            new_name='schedule_date',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
