# Generated by Django 5.2.1 on 2025-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
