services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py collectstatic --noinput &&
             python3 manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2"

    container_name: social-media
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      # no sync for production
      - ./:/app
      - ./files/profile:/files/profile
      - ./files/static:/files/static
    depends_on:
      social_db:
        condition: service_healthy
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-celery
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      social_db:
        condition: service_healthy
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-celery-beat
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      social_db:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:alpine
    container_name: social-nginx
    volumes:
      - ./nginx/:/etc/nginx/conf.d:ro/
      - ./files/profile:/files/profile
      - ./files/static:/files/static
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

  social_db:
    image: postgres:alpine
    container_name: social-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - social_db:$PGDATA
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart:
      always

volumes:
  social_db:
  social_media:
  social_static:
  redis_data: